
server:
  port: ${port:30013}
spring:
  datasource:
    url: jdbc:mysql://${db_url:192.168.5.93:3306/smop-sdc}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${username:root}
    password: ${password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      druid.initial-size: 10
      max-active: 1000
      min-idle: 5
      max-wait: 120000
      time-between-eviction-runs-millis: 120000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'X' FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    type: com.alibaba.druid.pool.DruidDataSource
    continue-on-error: false
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos-server:192.168.5.94:8848}
        group: ${NACOS_GROUP:soar}
  application:
    name: ${app-name:SDC-DATABUS-SOAR}
presto:
  table:
    logsearch:
      defname: log_template
  datasource:
    driverClassName: com.facebook.presto.jdbc.PrestoDriver
    url: jdbc:presto://192.168.5.92:16060/hive/xdr
    userName: brd
    available: false

mybatis-plus:
  type-aliases-package: com.broadtech.databus.soar.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#swagger
swagger:
  enable: true






